### PR TITLE
Match pipelines name exactly

### LINKED ISSUE #360: Partial matching behavior on tw pipelines command
The pipeline subcommand will return an error when there are multiple matches with the pipeline name. 

Example below:

```
mark@LAPTOP-CURHNF2E:~/scripts/tw$ ./tw pipelines view -n 'mark-slurm' -w 'seqeralabs/testing'

 ERROR: Multiple pipelines match 'mark-slurm' at [seqeralabs / testing] workspace

mark@LAPTOP-CURHNF2E:~/scripts/tw$ ./tw pipelines view -n 'hello-mark-slurm' -w 'seqeralabs/testing'

  Pipeline at [seqeralabs / testing] workspace:

    --------------+-------------------------------------------
     ID           | 10884606264418
     Name         | hello-mark-slurm
     Description  |
     Repository   | https://github.com/markpanganiban/nf-test
     Compute env. | mark-slurm
     Labels       | No labels found
```

### PR DESCRIPTION
**Pull request by JaimeSeqLabs**
## Description

Closes #360 

When searching a pipeline by name match the names exactly, not partially.

## Guidelines for testing

1.  Create a pipeline named `HelloWorld`
2. Create a second pipeline named `HelloWorldSecond`
3. When viewing pipelines by name the search matches the exact name and no "Multiple pipelines found" error is thrown.
```
$> ./tw pipelines view -n HelloWorld -w JaimeInc/Wsp

  Pipeline at [JaimeInc / Wsp] workspace:

    --------------+--------------------------------------
     ID           | 30153220095308                       
     Name         | HelloOptimization                    
     Description  |                                      
     Repository   | https://github.com/nextflow-io/hello 
     Compute env. | Org-batch-ce                         
     Labels       | owner=jaime                          

  Configuration:
....
```
4. When the name includes `"` characters they are escaped (and **the search should fail** because pipeline names can only contain aplhanumeric, dash and underscore)
```
$> ./tw pipelines view -n '"Hello"World"' -w JaimeInc/Wsp

 ERROR: Unknown pipeline '\"Hello\"Optimization\"' at [JaimeInc / Wsp] workspace

```

### CODE REVIEW

**Review by joaquimgamero — APPROVED** [review]
@JaimeSeqLabs I tested this through native compile and it works as described!

- Looking for pipeline `HelloWorld` in personal workspace:
Screenshot 2024-07-02 at 16 38 26

- Looking for pipeline `HelloWorldSecond` in personal workspace:
Screenshot 2024-07-02 at 16 39 21

- Looking for a pipeline including quotes fails:
Screenshot 2024-07-02 at 16 40 02

Let me know if you want me to test additional scenarios.

File: src/main/java/io/seqera/tower/cli/commands/pipelines/AbstractPipelinesCmd.java [hunk 1]
```diff
@@ -58,6 +63,21 @@ protected PipelineDbDto fetchPipeline(PipelineRefOptions pipelineRefOptions, Lon
...
 
+    private static String quotePipelineName(String pipelineName) {
+
+        if (pipelineName == null) return null;
+        if (pipelineName.isEmpty()) return "\"\"";
+
+        // replace '"' with '\"'
+        String escaped = pipelineName.replace("\"", "\\\"");
+
+        if (escaped.startsWith("\\\"") && escaped.endsWith("\\\"")) {
```
Comment (swampie) [inline src/main/java/io/seqera/tower/cli/commands/pipelines/AbstractPipelinesCmd.java:74]: what happens if only one side of the name has quotes?
Like `"pipeline` or `pipeline"`?

**Review by swampie — APPROVED** [review]
